export const friday = [
  {
    from: '11:00',
    to: '14:00',
    type: 'activity',
    by: 'JSDayUy',
    title: 'City Tour',
    notes: 'A tour through the most beautiful places on the city of Montevideo.',
  },
  {
    from: '16:00',
    to: '19:00',
    type: 'activity',
    by: 'Ingenious',
    title: 'SportsJS',
    notes:
      'Time to play some fútbol, basketball, ping-pong, and whatnot. Diversity first and mixed teams.',
  },
  {
    from: '17:00',
    to: '20:00',
    type: 'workshop',
    by: 'WyeWorks',
    title: 'GlimmerJS',
    notes: 'In this workshop you will learn how to ship a real world app with GlimmerJS.',
  },
  {
    from: '',
    to: '',
    type: 'workshop',
    by: 'IBM',
    title: 'Node-RED',
    notes:
      'In this workshop you will learn flow-based programming for the Internet of Things, using Node-RED.',
  },
];

export const saturday = [
  {
    from: '8:30',
    to: '9:30',
    type: 'meal',
    title: 'Breakfast',
    notes: '',
  },
  {
    from: '9:30',
    to: '9:45',
    type: 'keynote',
    by: 'Rodrigo Espinosa, Nacho Álvarez, Gabriel Chertok',
    title: 'Welcome to JSDayUY!',
    notes: '',
  },
  {
    from: '9:45',
    to: '10:30',
    type: 'keynote',
    by: 'Álvaro Videla',
    title: 'TBA',
    notes: '',
  },
  {
    from: '10:30',
    to: '10:45',
    type: 'meal',
    title: 'Coffee break',
    notes: '',
  },
  {
    from: '10:45',
    to: '11:15',
    type: 'talk',
    by: 'Karen Serfaty',
    title: 'TBA',
    notes: '',
  },
  {
    from: '11:15',
    to: '11:45',
    type: 'talk',
    by: 'Diego Muracciole',
    title: 'A journey through React renderers',
    notes: '',
  },
  {
    from: '11:45',
    to: '12:15',
    type: 'talk',
    by: 'Jean Carlo Emer',
    title: 'Types: why you should care',
    notes: '',
  },
  {
    from: '12:15',
    to: '13:00',
    type: 'meal',
    title: 'Lunch time',
    notes: '',
  },
  {
    from: '13:00',
    to: '13:30',
    type: 'talk',
    by: 'Mariano Campo',
    title: 'Building BarBot',
    notes: '',
  },
  {
    from: '13:30',
    to: '14:00',
    type: 'talk',
    by: ' Samanta de Barros',
    title: 'Progressive web apps',
    notes: '',
  },
  {
    from: '14:00',
    to: '14:30',
    type: 'meal',
    title: 'Coffee break',
    notes: '',
  },
  {
    from: '14:30',
    to: '15:00',
    type: 'talk',
    by: 'Federico Kauffman',
    title: 'Web Bluetooth painkillers',
    notes: '',
  },
  {
    from: '15:00',
    to: '15:30',
    type: 'talk',
    by: 'TBA',
    title: 'TBA',
    notes: '',
  },
  {
    from: '15:30',
    to: '16:00',
    type: 'meal',
    title: 'Coffee break',
    notes: '',
  },
  {
    from: '16:00',
    to: '16:30',
    type: 'talk',
    by: 'Mariano Vazquez',
    title: 'Why you should (not) build a reusable components library for your company',
    notes: '',
  },
  {
    from: '16:30',
    to: '17:00',
    type: 'talk',
    by: 'Martín Acosta',
    title: 'Microservices 4 real',
    notes: '',
  },
  {
    from: '17:00',
    to: '17:30',
    type: 'meal',
    title: 'Coffee Break',
    notes: '',
  },
  {
    from: '17:30',
    to: '18:00',
    type: 'talk',
    by: 'Alejandro Narancio',
    title: 'Distributed applications using Ethereum and web3js',
    notes: '',
  },
  {
    from: '18:00',
    to: '19:00',
    type: 'keynote',
    by: 'Gonto',
    title: 'Let the world know about your open source project',
    notes: '',
  },
  {
    from: '19:00',
    to: '4EVER',
    type: 'recreation',
    title: 'Drinkup Party! 🍻🎉',
    notes: '',
  },
];
